"""Parse docs/results.md into docs/paper/skeleton.md.

For each `### R-<name>: <title>   (YYYY-MM-DD)` heading in results.md we
extract:
  * title + date
  * setup summary (first bullet under "Setup:")
  * result tables (any markdown table under "Result" up to the next `- **`)
  * one-line interpretation (first sentence of "Interpretation:")
  * paired-stat p-value if present

and emit them as a paper-skeleton appendix with a placeholder for the
figure caption. The point is not to write the paper — it's to have a
one-command way to keep the paper appendix in sync with the current
results ledger, which is Gate G's "paper skeleton has real results tables"
deliverable.

Usage:
    python -m scripts.build_paper_skeleton
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS = ROOT / "docs" / "results.md"
DEFAULT_OUT = ROOT / "docs" / "paper" / "skeleton.md"

R_HEADER = re.compile(
    r"^### R-([^:]+):\s+(.+?)\s{2,}\(([\d]{4}-[\d]{2}-[\d]{2})\)\s*$",
    re.MULTILINE,
)


def _extract_sections(text: str) -> list[dict]:
    """Split results.md into per-entry blocks and pull out interesting fields."""
    positions = [(m.start(), m.group(1).strip(), m.group(2).strip(), m.group(3).strip())
                 for m in R_HEADER.finditer(text)]
    positions.append((len(text), "END", "", ""))
    entries: list[dict] = []
    for i in range(len(positions) - 1):
        start, tag, title, date = positions[i]
        end, _, _, _ = positions[i + 1]
        body = text[start:end]
        entries.append({
            "tag": tag,
            "title": title,
            "date": date,
            "body": body,
            "setup": _first_bullet(body, "Setup:"),
            "interpretation": _first_bullet(body, "Interpretation"),
            "wilcoxon_p": _extract_p_value(body),
            "tables": _extract_tables(body),
        })
    return entries


def _first_bullet(body: str, header: str) -> str:
    m = re.search(rf"\*\*{re.escape(header)}\**\s*\*\*\s*(.+?)(?=\n- \*\*|\n---|\Z)", body, re.S)
    if not m:
        return ""
    text = m.group(1).strip()
    # Squash whitespace so we get roughly the first meaningful sentence.
    text = re.sub(r"\s+", " ", text)
    # Return first ~450 chars ending on a period.
    if len(text) > 450:
        cut = text[:450].rsplit(".", 1)
        text = cut[0].strip() + "." if cut else text[:450]
    return text


def _extract_p_value(body: str) -> float | None:
    # Look for "p = 0.0xxx" or "p=0.0xxx" or "**p = 0.0xxx**"
    matches = re.findall(r"[pP]\s*=\s*\*{0,2}([0-9]*\.?[0-9]+)\*{0,2}", body)
    for m in matches:
        try:
            v = float(m)
            if 0.0 <= v <= 1.0:
                return v
        except ValueError:
            continue
    return None


def _extract_tables(body: str) -> list[str]:
    """Return every markdown table block in the entry body."""
    lines = body.splitlines()
    tables: list[list[str]] = []
    cur: list[str] = []
    in_table = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            cur.append(line.rstrip())
            in_table = True
        else:
            if in_table and cur:
                tables.append(cur)
                cur = []
            in_table = False
    if cur:
        tables.append(cur)
    # Deduplicate + drop the frontmatter template table at the top of the file.
    unique: list[str] = []
    seen: set[str] = set()
    for t in tables:
        joined = "\n".join(t).strip()
        if not joined or joined in seen:
            continue
        seen.add(joined)
        unique.append(joined)
    return unique


def _render(entries: list[dict], src_path: Path) -> str:
    lines: list[str] = [
        "# CADENCE — Paper Skeleton (auto-generated appendix)",
        "",
        f"Generated by `python -m scripts.build_paper_skeleton` from `{src_path.relative_to(ROOT)}`.",
        "Every entry below points back to a live R-record in the results ledger and to the",
        "exact `experiments/*.json` artifact that produced its numbers.",
        "",
        "## Section map",
        "",
    ]
    for e in entries:
        lines.append(f"- [{e['tag']}: {e['title']}](#{'r-' + e['tag'].lower().replace('.', '-')})")
    lines.append("")
    lines.append("## Result tables (one section per R-entry)")
    lines.append("")
    for e in entries:
        anchor_tag = e["tag"].lower().replace(".", "-")
        lines.append(f"### R-{e['tag']}: {e['title']}")
        lines.append(f"*Recorded: {e['date']}*")
        lines.append("")
        if e["setup"]:
            lines.append(f"**Setup.** {e['setup']}")
            lines.append("")
        if e["wilcoxon_p"] is not None:
            marker = "PASS" if e["wilcoxon_p"] < 0.05 else "borderline / negative"
            lines.append(f"**Statistical test.** paired Wilcoxon p ≈ {e['wilcoxon_p']:.4g} → {marker} at α=0.05")
            lines.append("")
        if e["tables"]:
            for tbl in e["tables"]:
                lines.append(tbl)
                lines.append("")
        else:
            lines.append("_No tables extracted — see the raw entry in `docs/results.md`._")
            lines.append("")
        if e["interpretation"]:
            lines.append(f"**Interpretation.** {e['interpretation']}")
            lines.append("")
        lines.append("**Figure placeholder.** _TODO: insert plot referencing this entry's `experiments/*.json` artifact._")
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--results", default=str(DEFAULT_RESULTS))
    p.add_argument("--out", default=str(DEFAULT_OUT))
    args = p.parse_args()

    src = Path(args.results)
    dst = Path(args.out)
    text = src.read_text(encoding="utf-8")
    entries = _extract_sections(text)
    # Filter to real R-entries (skip the template placeholder like R-<n>).
    entries = [e for e in entries if not e["tag"].startswith("<")]
    md = _render(entries, src)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(md, encoding="utf-8")
    print(f"wrote {dst.relative_to(ROOT)}  ({len(entries)} R-entries, {sum(len(e['tables']) for e in entries)} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
